defaults:
  - model: vit

patch_size: 32
split: overlap
slide_step: 24
hidden_size: 768
dropout: 0.1
max_len: 100
classifier: token
num_classes: 200
batch_size: 16
num_workers: 16
image_size: 448
transformer:
  mlp_dim: 3072
  num_heads: 12
  num_layers: 12
lr: 1e-2
seed: 42
momentum: 0.9
epoch: 10000
gpus: 2
logger: true
patience: 50
pretrained_dir: /home/lorenzo/xfg/pretrained/vit/imagenet21k_ViT-B_32.npz
root: "/home/lorenzo/xfg/data"
warmup: false